name: Deploy PHP Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy Application
      env:
        TARGET_PATH: ${{ secrets.TARGET_PATH }}
      run: |
        find . -path ./.git -prune -o -path ./.github -prune -o -exec cp -R --parents {} $TARGET_PATH \;