name: Deploy PHP Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Deploy Application
      env:
        TARGET_PATH: /var/www/edend12.imtbs-tsp.eu
      run: |
        cp -R $TARGET_PATH $TARGET_PATH.bak
        find . -path ./.git -prune -o -path ./.github -prune -o -exec cp -R --parents {} $TARGET_PATH \;