name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy-eden:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy EDEN
        if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.message, 'website') || contains(join(github.event.commits.*.modified, ''), 'website/')) }}
        env:
          TARGET_PATH: /var/www/edend12.imtbs-tsp.eu
        run: |
          rm -rf $TARGET_PATH.bak
          cp -R $TARGET_PATH $TARGET_PATH.bak
          cp -R ./website $TARGET_PATH

  copy-proxy-config:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy Proxy
        if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.message, 'proxy') || contains(join(github.event.commits.*.modified, ''), 'proxy/')) }}
        env:
          TARGET_PATH: /opt/EDEN/proxy
        run: |
          rm -rf $TARGET_PATH.bak
          cp -R $TARGET_PATH $TARGET_PATH.bak
          cp -R ./proxy $TARGET_PATH

  copy-tofu-config:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy Tofu
        if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.message, 'tofu') || contains(join(github.event.commits.*.modified, ''), 'tofu/')) }}
        env:
          TARGET_PATH: /var/www/tofu
        run: |
          rm -rf $TARGET_PATH.bak
          cp -R $TARGET_PATH $TARGET_PATH.bak
          cp -R ./tofu $TARGET_PATH

  copy-dns-config:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy DNS
        if: ${{ github.event_name == 'push' && (contains(github.event.head_commit.message, 'dns') || contains(join(github.event.commits.*.modified, ''), 'dns/')) }}
        env:
          TARGET_PATH: /opt/EDEN/dns
        run: |
          rm -rf $TARGET_PATH.bak
          cp -R $TARGET_PATH $TARGET_PATH.bak
          cp -R ./dns $TARGET_PATH